### ISSUE TITLE
coredump

### ISSUE THREAD

**Issue by sevu** [fishilico/funguloids#1]
Thanks for maintaining this.
The sheer numbers of patches is awesome.

With the current version I do get a segfault upon launch. Could you maybe try to fix it too?
I suspect it's due to an ogre update, as usual.

```
$ funguloids     
Creating resource group General
Creating resource group OgreInternal
Creating resource group OgreAutodetect
SceneManagerFactory for type 'DefaultSceneManager' registered.
Registering ResourceManager for type Material
Registering ResourceManager for type Mesh
Registering ResourceManager for type Skeleton
MovableObjectFactory for type 'ParticleSystem' registered.
ArchiveFactory for archive type FileSystem registered.
ArchiveFactory for archive type Zip registered.
ArchiveFactory for archive type EmbeddedZip registered.
DDS codec registering
ETC codec registering
Registering ResourceManager for type HighLevelGpuProgram
Registering ResourceManager for type Compositor
MovableObjectFactory for type 'Entity' registered.
MovableObjectFactory for type 'Light' registered.
MovableObjectFactory for type 'BillboardSet' registered.
MovableObjectFactory for type 'ManualObject' registered.
MovableObjectFactory for type 'BillboardChain' registered.
MovableObjectFactory for type 'RibbonTrail' registered.
Loading library /usr/lib/OGRE/Codec_FreeImage
FreeImage version: 3.18.0
This program uses FreeImage, a free, open source image library supporting all common bitmap formats. See http://freeimage.sourceforge.net for details
Supported formats: bmp,ico,jpg,jif,jpeg,jpe,jng,koa,iff,lbm,mng,pbm,pbm,pcd,pcx,pgm,pgm,png,ppm,ppm,ras,tga,targa,tif,tiff,wap,wbmp,wbm,psd,psb,cut,xbm,xpm,gif,hdr,sgi,rgb,rgba,bw,exr,j2k,j2c,jp2,pfm,pct,pict,pic,3fr,arw,bay,bmq,cap,cine,cr2,crw,cs1,dc2,dcr,drf,dsc,dng,erf,fff,ia,iiq,k25,kc2,kdc,mdc,mef,mos,mrw,nef,nrw,orf,pef,ptx,pxn,qtk,raf,raw,rdc,rw2,rwl,rwz,sr2,srf,srw,sti,x3f,webp,jxr,wdp,hdp
Loading library /usr/lib/OGRE/RenderSystem_GL
Installing plugin: GL RenderSystem
OpenGL Rendering Subsystem created.
Plugin successfully installed
Loading library /usr/lib/OGRE/Plugin_ParticleFX
Installing plugin: ParticleFX
Particle Emitter Type 'Point' registered
Particle Emitter Type 'Box' registered
Particle Emitter Type 'Ellipsoid' registered
Particle Emitter Type 'Cylinder' registered
Particle Emitter Type 'Ring' registered
Particle Emitter Type 'HollowEllipsoid' registered
Particle Affector Type 'LinearForce' registered
Particle Affector Type 'ColourFader' registered
Particle Affector Type 'ColourFader2' registered
Particle Affector Type 'ColourImage' registered
Particle Affector Type 'ColourInterpolator' registered
Particle Affector Type 'Scaler' registered
Particle Affector Type 'Rotator' registered
Particle Affector Type 'DirectionRandomiser' registered
Particle Affector Type 'DeflectorPlane' registered
Plugin successfully installed
Loading library /usr/lib/OGRE/Plugin_OctreeSceneManager
Installing plugin: Octree Scene Manager
Plugin successfully installed
Loading library /usr/lib/OGRE/Plugin_CgProgramManager
Installing plugin: Cg Program Manager
Plugin successfully installed
*-*-* OGRE Initialising
*-*-* Version 1.11.2 (Rhagorthua)
OverlayElementFactory for type Panel registered.
OverlayElementFactory for type BorderPanel registered.
OverlayElementFactory for type TextArea registered.
Registering ResourceManager for type Font
ArchiveFactory for archive type MPK registered.
Creating resource group Bootstrap
Added resource location '/usr/share/funguloids/bootstrap.mpk' of type 'MPK' to resource group 'Bootstrap'
Added resource location '/usr/share/funguloids/music' of type 'FileSystem' to resource group 'General'
Added resource location '/usr/share/funguloids/icon' of type 'FileSystem' to resource group 'General'
Added resource location '/usr/share/funguloids/funguloids.mpk' of type 'MPK' to resource group 'General'
An exception has occured: InvalidParametersException: Option named Fixed Pipeline Enabled does not exist. in GLNativeSupport::setConfigOption at /build/ogre/src/ogre-1.11.2/RenderSystems/GLSupport/src/OgreGLRenderSystemCommon.cpp (line 229)Segmentation fault (core dumped)
```
I don't know how to build with debugging information, so the coredump is rather useless.

**Comment by fishilico** [comment]
You're welcome ! And thanks for this bug report. Unfortunately I have updated my system (with OGRE 1.11.2-2) and it works fine on my system. The error you get seems to point to OGRE configuration file (for example `$HOME/.funguloids/ogre.cfg`. Which file contains `"Fixed Pipeline Enabled"` on your system? Could you try running funguloids from a new user account (with a clean `$HOME`)?

**Comment by sevu** [comment]
I had indeed an autogenerated ogre.cfg from 2016 in this directory.
Removing the directory let's the game start again and does not create a new ogre.cfg. However, in a very small window, and not in fullscreen mode.
Using the old ogre.cfg and removing that line works. I wonder if that may be a problem for new users.

My ogre.cfg looks now like this:
```
Render System=OpenGL Rendering Subsystem

[OpenGL Rendering Subsystem]
Display Frequency=60 Hz
FSAA=0
Full Screen=Yes
RTT Preferred Mode=FBO
VSync=No
Video Mode=1920 x 1080
sRGB Gamma Conversion=No
```

**Comment by fishilico** [comment]
Good catch! In previous version of the game, there was an OGRE settings window displayed when starting the game (cf. http://funguloids.sourceforge.net/readme.html#howtoplay ). This window has not been displayed since OGRE 1.10.8: I modified `mRoot->showConfigDialog()` to `mRoot->showConfigDialog(NULL)` in https://github.com/fishilico/funguloids/commit/43576bb988762aa8fc63e5f7fbc211d1a8654802#diff-6111b0cafa5f9d6133eda2e496ef1e41R106 (because `showConfigDialog(void)` is deprecated), and this does not display anything.

According to OGRE configuration, `OgreBites::getNativeConfigDialog()` needs to be used to build a config dialog which is then passed to `showConfigDialog`. I am testing something like this (in `src/ogreapp.cpp`), which seems to solve the issue:
```c
	if(!mRoot->restoreConfig()) {
		if(!mRoot->showConfigDialog(OgreBites::getNativeConfigDialog()))
			return false;
```

I will update the program and release a new version of the package.

**Comment by sevu** [comment]
Thank you very much.
Something seems to be fishy still.
If I have no `~/.funguloids` directory, stderr (ignoring stdout) prints:
```
Warning: Unable to load any usable ISO8859 font
Error: Aborting: no font found
```
and exits.

That's the one observation, the other is: I could start the game with my old config files after installation. I'm not exactly sure how this worked as I couldn't reproduce it later, but…
There are files created in `~./fungluoids`, and it seems that at least some of my files were in `~/.fungluoids/fungluoids`. E.g. taking the highscore.lst as example, I have it in the later, but saw later that it appeared in the former, maybe due to a new highscore.
